from enum import Enum
from typing import List


class ExtendedEnum(Enum):
    @classmethod
    def list_values(cls) -> List[str]:
        return [e.value for e in cls]

    @classmethod
    def list_names(cls) -> List[str]:
        return [e.name for e in cls]


class TickerSymbol(ExtendedEnum):
    AAPL = "AAPL"
    MSFT = "MSFT"
    GOOGL = "GOOGL"
    AMZN = "AMZN"
    TSLA = "TSLA"
    V = "V"
    JNJ = "JNJ"
    WMT = "WMT"
    JPM = "JPM"
    NVDA = "NVDA"
    PG = "PG"
    DIS = "DIS"
    MA = "MA"
    HD = "HD"
    PYPL = "PYPL"
    VZ = "VZ"
    ADBE = "ADBE"
    NFLX = "NFLX"
    INTC = "INTC"
    CMCSA = "CMCSA"
    PFE = "PFE"
    KO = "KO"
    PEP = "PEP"
    MRK = "MRK"
    T = "T"
    CSCO = "CSCO"
    XOM = "XOM"
    ABT = "ABT"
    CVX = "CVX"
    NKE = "NKE"
    LLY = "LLY"
    MCD = "MCD"
    MDT = "MDT"
    CRM = "CRM"
    BMY = "BMY"
    UNH = "UNH"
    HON = "HON"
    WFC = "WFC"
    COST = "COST"
    AMGN = "AMGN"
    ACN = "ACN"
    AVGO = "AVGO"
    TXN = "TXN"
    QCOM = "QCOM"
    NEE = "NEE"
    IBM = "IBM"
    LIN = "LIN"
    PM = "PM"
    ORCL = "ORCL"
    UPS = "UPS"
    SBUX = "SBUX"
    MS = "MS"
    GS = "GS"
    BLK = "BLK"
    RTX = "RTX"
    CAT = "CAT"
    MMM = "MMM"
    SPGI = "SPGI"
    BA = "BA"
    GE = "GE"
    TMO = "TMO"
    ISRG = "ISRG"
    NOW = "NOW"
    DHR = "DHR"
    LMT = "LMT"
    MDLZ = "MDLZ"
    SYK = "SYK"
    CVS = "CVS"
    AMT = "AMT"
    ADI = "ADI"
    ZTS = "ZTS"
    GILD = "GILD"
    BKNG = "BKNG"
    FIS = "FIS"
    PLD = "PLD"
    CI = "CI"
    SCHW = "SCHW"
    CB = "CB"
    USB = "USB"
    PNC = "PNC"
    MMC = "MMC"
    CCI = "CCI"
    ADP = "ADP"
    DUK = "DUK"
    SO = "SO"
    BDX = "BDX"
    APD = "APD"
    CL = "CL"
    ICE = "ICE"
    ECL = "ECL"
    ITW = "ITW"
    NSC = "NSC"
    ETN = "ETN"
    AON = "AON"
    WM = "WM"
    TGT = "TGT"
    DE = "DE"
    FDX = "FDX"
    HUM = "HUM"
